//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CeVIO.ToolBarControl.Properties.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ja_JP {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ja_JP() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CeVIO.ToolBarControl.Properties.Resources.ja-JP", typeof(ja_JP).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 选择工具 [Ctrl+1]
        ///乐谱编辑：选择（单个或范围）音符或标记。
        ///调整界面：指定复制或删除的范围。按住Alt键不吸附量化线。
        ///（按住左Ctrl：画笔工具） 的本地化字符串。
        /// </summary>
        public static string ArrowButtonToolTip {
            get {
                return ResourceManager.GetString("ArrowButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 播放时自动滚动 [F7] 的本地化字符串。
        /// </summary>
        public static string AutoScrollButtonToolTip {
            get {
                return ResourceManager.GetString("AutoScrollButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 起点标记 的本地化字符串。
        /// </summary>
        public static string BeginMarkerButtonToolTip {
            get {
                return ResourceManager.GetString("BeginMarkerButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 范围选择工具 [Ctrl+2]
        ///选择范围内所有的音符或参数值。按住Alt键不吸附量化线。
        ///（按住左Ctrl：画笔工具） 的本地化字符串。
        /// </summary>
        public static string BulkButtonToolTip {
            get {
                return ResourceManager.GetString("BulkButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 音高(PIT)调整 [4]
        ///调整每个音每个时刻的音高（不考虑颤音）。
        ///当与VIA/VIF参数重叠显示时，会额外显示颤音的效果。 的本地化字符串。
        /// </summary>
        public static string EditPitchButtonToolTip {
            get {
                return ResourceManager.GetString("EditPitchButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 乐谱编辑 [1] 的本地化字符串。
        /// </summary>
        public static string EditScoreButtonToolTip {
            get {
                return ResourceManager.GetString("EditScoreButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间(TMG)调整 [2]
        ///点击PIT等按钮的文字部分可以重叠显示。
        ///拖动黑色方框的边界线，可以对整个音符及前后的状态进行整体调整。 的本地化字符串。
        /// </summary>
        public static string EditTimingButtonToolTip {
            get {
                return ResourceManager.GetString("EditTimingButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 颤音振幅(VIA)调整 [5]
        ///点击PIT等按钮的文字部分可以重叠显示。 的本地化字符串。
        /// </summary>
        public static string EditVibratoAmplitudeButtonToolTip {
            get {
                return ResourceManager.GetString("EditVibratoAmplitudeButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 颤音周期(VIF)调整 [6]
        ///点击PIT等按钮的文字部分可以重叠显示。 的本地化字符串。
        /// </summary>
        public static string EditVibratoFrequencyButtonToolTip {
            get {
                return ResourceManager.GetString("EditVibratoFrequencyButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 音量(VOL)调整 [3]
        ///点击PIT等按钮的文字部分可以重叠显示。 的本地化字符串。
        /// </summary>
        public static string EditVolumeButtonToolTip {
            get {
                return ResourceManager.GetString("EditVolumeButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 终点标记 的本地化字符串。
        /// </summary>
        public static string EndMarkerButtonToolTip {
            get {
                return ResourceManager.GetString("EndMarkerButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 橡皮擦工具 [Ctrl+5]
        ///乐谱编辑：删除音符或标记。。
        ///調整界面：清除参数的调整值。(PIT/VIA/VIF)按住Shift绘制可将原始值也无效化。
        ///（按住左Ctrl：选择工具） 的本地化字符串。
        /// </summary>
        public static string EraserButtonToolTip {
            get {
                return ResourceManager.GetString("EraserButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回开头 [小键盘 .] 的本地化字符串。
        /// </summary>
        public static string HeadButtonToolTip {
            get {
                return ResourceManager.GetString("HeadButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 光标处的拍子
        ///点击以修改。将会添加到钢琴卷帘的拍子行。 的本地化字符串。
        /// </summary>
        public static string Indicator_BeatToolTip {
            get {
                return ResourceManager.GetString("Indicator_BeatToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1/16(3连音) 的本地化字符串。
        /// </summary>
        public static string Indicator_QuantizeMenu_Triplet16 {
            get {
                return ResourceManager.GetString("Indicator_QuantizeMenu_Triplet16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1/2(3连音) 的本地化字符串。
        /// </summary>
        public static string Indicator_QuantizeMenu_Triplet2 {
            get {
                return ResourceManager.GetString("Indicator_QuantizeMenu_Triplet2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1/4(3连音) 的本地化字符串。
        /// </summary>
        public static string Indicator_QuantizeMenu_Triplet4 {
            get {
                return ResourceManager.GetString("Indicator_QuantizeMenu_Triplet4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1/8(3连音) 的本地化字符串。
        /// </summary>
        public static string Indicator_QuantizeMenu_Triplet8 {
            get {
                return ResourceManager.GetString("Indicator_QuantizeMenu_Triplet8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 音符量化
        ///点击以更换。 的本地化字符串。
        /// </summary>
        public static string Indicator_QuantizeToolTip {
            get {
                return ResourceManager.GetString("Indicator_QuantizeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 光标处的曲速
        ///点击以修改。将会添加到钢琴卷帘的节奏行。 的本地化字符串。
        /// </summary>
        public static string Indicator_TempoToolTip {
            get {
                return ResourceManager.GetString("Indicator_TempoToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小节 的本地化字符串。
        /// </summary>
        public static string Indicator_TimeMenu_Bars {
            get {
                return ResourceManager.GetString("Indicator_TimeMenu_Bars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 秒 的本地化字符串。
        /// </summary>
        public static string Indicator_TimeMenu_Seconds {
            get {
                return ResourceManager.GetString("Indicator_TimeMenu_Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间轴光标位置
        ///鼠标左键指定位置。鼠标右键切换显示方式。 的本地化字符串。
        /// </summary>
        public static string Indicator_TimeToolTip {
            get {
                return ResourceManager.GetString("Indicator_TimeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 直线工具 [Ctrl+4]
        ///乐谱编辑：与画笔工具相同。
        ///调整界面：(除TMG外)绘制直线。按住Alt绘制则可被原始值切断。按住Shift绘制水平线。
        ///（按住左Ctrl：橡皮擦工具） 的本地化字符串。
        /// </summary>
        public static string LineButtonToolTip {
            get {
                return ResourceManager.GetString("LineButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 画笔工具 [Ctrl+3]
        ///乐谱编辑：输入（或移动）音符或标记。
        ///调整界面：调整参数值。按住Alt绘制则可被原始值切断。
        ///（按住左Ctrl：橡皮擦工具） 的本地化字符串。
        /// </summary>
        public static string PenButtonToolTip {
            get {
                return ResourceManager.GetString("PenButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 播放 [Space] 的本地化字符串。
        /// </summary>
        public static string PlayButtonToolTip {
            get {
                return ResourceManager.GetString("PlayButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 循环 [小键盘 /] 的本地化字符串。
        /// </summary>
        public static string RepeatButtonToolTip {
            get {
                return ResourceManager.GetString("RepeatButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示音高
        ///当重叠显示时会额外显示颤音效果。 的本地化字符串。
        /// </summary>
        public static string ShowPitchButtonToolTip {
            get {
                return ResourceManager.GetString("ShowPitchButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示时间 的本地化字符串。
        /// </summary>
        public static string ShowTimingButtonToolTip {
            get {
                return ResourceManager.GetString("ShowTimingButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示颤音振幅 的本地化字符串。
        /// </summary>
        public static string ShowVibratoAmplitudeButtonToolTip {
            get {
                return ResourceManager.GetString("ShowVibratoAmplitudeButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示颤音周期 的本地化字符串。
        /// </summary>
        public static string ShowVibratoFrequencyButtonToolTip {
            get {
                return ResourceManager.GetString("ShowVibratoFrequencyButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示音量 的本地化字符串。
        /// </summary>
        public static string ShowVolumeButtonToolTip {
            get {
                return ResourceManager.GetString("ShowVolumeButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止 [小键盘 0]
        ///停止状态下再点击会依次回到播放开始位置、歌曲开头。 的本地化字符串。
        /// </summary>
        public static string StopButtonToolTip {
            get {
                return ResourceManager.GetString("StopButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 水平显示位置(_V) 的本地化字符串。
        /// </summary>
        public static string ToolBarMenu_HorizontalLocation {
            get {
                return ResourceManager.GetString("ToolBarMenu_HorizontalLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中间 的本地化字符串。
        /// </summary>
        public static string ToolBarMenu_HorizontalLocationCenter {
            get {
                return ResourceManager.GetString("ToolBarMenu_HorizontalLocationCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 左侧 的本地化字符串。
        /// </summary>
        public static string ToolBarMenu_HorizontalLocationLeft {
            get {
                return ResourceManager.GetString("ToolBarMenu_HorizontalLocationLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 右侧 的本地化字符串。
        /// </summary>
        public static string ToolBarMenu_HorizontalLocationRight {
            get {
                return ResourceManager.GetString("ToolBarMenu_HorizontalLocationRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 垂直显示位置(_H) 的本地化字符串。
        /// </summary>
        public static string ToolBarMenu_VerticalLocation {
            get {
                return ResourceManager.GetString("ToolBarMenu_VerticalLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 底部 的本地化字符串。
        /// </summary>
        public static string ToolBarMenu_VerticalLocationBottom {
            get {
                return ResourceManager.GetString("ToolBarMenu_VerticalLocationBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中间 的本地化字符串。
        /// </summary>
        public static string ToolBarMenu_VerticalLocationMiddle {
            get {
                return ResourceManager.GetString("ToolBarMenu_VerticalLocationMiddle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 顶部 的本地化字符串。
        /// </summary>
        public static string ToolBarMenu_VerticalLocationTop {
            get {
                return ResourceManager.GetString("ToolBarMenu_VerticalLocationTop", resourceCulture);
            }
        }
    }
}
