//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CeVIO.ToolBarControl.Properties.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class zh_CN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal zh_CN() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CeVIO.ToolBarControl.Properties.Resources.zh-CN", typeof(zh_CN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 選択ツール [Ctrl+1]
        ///楽譜編集：音符やテンポなどの選択、音符の範囲選択。
        ///調整画面：コピーや削除の範囲指定。Alt押下でクオンタイズなし。
        ///(左Ctrl押下中：ペンツール) 的本地化字符串。
        /// </summary>
        public static string ArrowButtonToolTip {
            get {
                return ResourceManager.GetString("ArrowButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 再生中の自動スクロール [F7] 的本地化字符串。
        /// </summary>
        public static string AutoScrollButtonToolTip {
            get {
                return ResourceManager.GetString("AutoScrollButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 始点マーカー 的本地化字符串。
        /// </summary>
        public static string BeginMarkerButtonToolTip {
            get {
                return ResourceManager.GetString("BeginMarkerButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 まとめ選択ツール [Ctrl+2]
        ///範囲内の音符と全調整値をまとめて選択。Alt押下でクオンタイズなし。
        ///(左Ctrl押下中：ペンツール) 的本地化字符串。
        /// </summary>
        public static string BulkButtonToolTip {
            get {
                return ResourceManager.GetString("BulkButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ピッチを調整 [4]
        ///ビブラートを含まない基本ピッチを調整。
        ///VIA,VIFを重ねるとビブラート反映ピッチも重ね表示。 的本地化字符串。
        /// </summary>
        public static string EditPitchButtonToolTip {
            get {
                return ResourceManager.GetString("EditPitchButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 楽譜を編集 [1] 的本地化字符串。
        /// </summary>
        public static string EditScoreButtonToolTip {
            get {
                return ResourceManager.GetString("EditScoreButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 タイミングを調整 [2]
        ///PIT等の文字クリックで重ね表示。
        ///下段の黒背景の音素ラインをドラッグすると前後の状態ラインも連動。 的本地化字符串。
        /// </summary>
        public static string EditTimingButtonToolTip {
            get {
                return ResourceManager.GetString("EditTimingButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ビブラートの振幅を調整 [5]
        ///PIT等の文字クリックで重ね表示。 的本地化字符串。
        /// </summary>
        public static string EditVibratoAmplitudeButtonToolTip {
            get {
                return ResourceManager.GetString("EditVibratoAmplitudeButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ビブラートの周期を調整 [6]
        ///PIT等の文字クリックで重ね表示。 的本地化字符串。
        /// </summary>
        public static string EditVibratoFrequencyButtonToolTip {
            get {
                return ResourceManager.GetString("EditVibratoFrequencyButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ボリュームを調整 [3]
        ///PIT等の文字クリックで重ね表示。 的本地化字符串。
        /// </summary>
        public static string EditVolumeButtonToolTip {
            get {
                return ResourceManager.GetString("EditVolumeButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 終点マーカー 的本地化字符串。
        /// </summary>
        public static string EndMarkerButtonToolTip {
            get {
                return ResourceManager.GetString("EndMarkerButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 消しゴムツール [Ctrl+5]
        ///楽譜編集：音符やテンポなどを削除。
        ///調整画面：調整した値を削除。(PIT/VIA/VIF)Shift押下で元の値を無効化。
        ///(左Ctrl押下中：選択ツール) 的本地化字符串。
        /// </summary>
        public static string EraserButtonToolTip {
            get {
                return ResourceManager.GetString("EraserButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 先頭 [テンキーの.] 的本地化字符串。
        /// </summary>
        public static string HeadButtonToolTip {
            get {
                return ResourceManager.GetString("HeadButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ポジションカーソル位置の拍子
        ///クリックで変更。追加はピアノロールの拍子行。 的本地化字符串。
        /// </summary>
        public static string Indicator_BeatToolTip {
            get {
                return ResourceManager.GetString("Indicator_BeatToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1/16(3連符) 的本地化字符串。
        /// </summary>
        public static string Indicator_QuantizeMenu_Triplet16 {
            get {
                return ResourceManager.GetString("Indicator_QuantizeMenu_Triplet16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1/2(3連符) 的本地化字符串。
        /// </summary>
        public static string Indicator_QuantizeMenu_Triplet2 {
            get {
                return ResourceManager.GetString("Indicator_QuantizeMenu_Triplet2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1/4(3連符) 的本地化字符串。
        /// </summary>
        public static string Indicator_QuantizeMenu_Triplet4 {
            get {
                return ResourceManager.GetString("Indicator_QuantizeMenu_Triplet4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1/8(3連符) 的本地化字符串。
        /// </summary>
        public static string Indicator_QuantizeMenu_Triplet8 {
            get {
                return ResourceManager.GetString("Indicator_QuantizeMenu_Triplet8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 音符のクオンタイズ
        ///クリックで切替。 的本地化字符串。
        /// </summary>
        public static string Indicator_QuantizeToolTip {
            get {
                return ResourceManager.GetString("Indicator_QuantizeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ポジションカーソル位置のテンポ
        ///クリックで変更。追加はピアノロールのテンポ行。 的本地化字符串。
        /// </summary>
        public static string Indicator_TempoToolTip {
            get {
                return ResourceManager.GetString("Indicator_TempoToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小節 的本地化字符串。
        /// </summary>
        public static string Indicator_TimeMenu_Bars {
            get {
                return ResourceManager.GetString("Indicator_TimeMenu_Bars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 秒 的本地化字符串。
        /// </summary>
        public static string Indicator_TimeMenu_Seconds {
            get {
                return ResourceManager.GetString("Indicator_TimeMenu_Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ポジションカーソルの位置
        ///左クリックで位置指定。右クリックで秒／小節の表示切替。 的本地化字符串。
        /// </summary>
        public static string Indicator_TimeToolTip {
            get {
                return ResourceManager.GetString("Indicator_TimeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ラインツール [Ctrl+4]
        ///楽譜編集：ペンツールと同じ働き。
        ///調整画面：(TMG以外)直線を引く。Alt押下で既定値接続調整。Shift押下で水平線。
        ///(左Ctrl押下中：消しゴムツール) 的本地化字符串。
        /// </summary>
        public static string LineButtonToolTip {
            get {
                return ResourceManager.GetString("LineButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ペンツール [Ctrl+3]
        ///楽譜編集：音符やテンポなどの入力や選択、移動。
        ///調整画面：値を調整。Alt押下で既定値接続調整。
        ///(左Ctrl押下中：消しゴムツール) 的本地化字符串。
        /// </summary>
        public static string PenButtonToolTip {
            get {
                return ResourceManager.GetString("PenButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 再生 [Space] 的本地化字符串。
        /// </summary>
        public static string PlayButtonToolTip {
            get {
                return ResourceManager.GetString("PlayButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 繰り返し [テンキーの/] 的本地化字符串。
        /// </summary>
        public static string RepeatButtonToolTip {
            get {
                return ResourceManager.GetString("RepeatButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ピッチを表示
        ///重ね表示にはビブラートを反映。 的本地化字符串。
        /// </summary>
        public static string ShowPitchButtonToolTip {
            get {
                return ResourceManager.GetString("ShowPitchButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 タイミングを表示 的本地化字符串。
        /// </summary>
        public static string ShowTimingButtonToolTip {
            get {
                return ResourceManager.GetString("ShowTimingButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ビブラートの振幅を表示 的本地化字符串。
        /// </summary>
        public static string ShowVibratoAmplitudeButtonToolTip {
            get {
                return ResourceManager.GetString("ShowVibratoAmplitudeButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ビブラートの周期を表示 的本地化字符串。
        /// </summary>
        public static string ShowVibratoFrequencyButtonToolTip {
            get {
                return ResourceManager.GetString("ShowVibratoFrequencyButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ボリュームを表示 的本地化字符串。
        /// </summary>
        public static string ShowVolumeButtonToolTip {
            get {
                return ResourceManager.GetString("ShowVolumeButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止 [テンキーの0]
        ///停止中は再生開始位置、先頭の順に移動。 的本地化字符串。
        /// </summary>
        public static string StopButtonToolTip {
            get {
                return ResourceManager.GetString("StopButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 左右の表示位置(_V) 的本地化字符串。
        /// </summary>
        public static string ToolBarMenu_HorizontalLocation {
            get {
                return ResourceManager.GetString("ToolBarMenu_HorizontalLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中央 的本地化字符串。
        /// </summary>
        public static string ToolBarMenu_HorizontalLocationCenter {
            get {
                return ResourceManager.GetString("ToolBarMenu_HorizontalLocationCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 左寄せ 的本地化字符串。
        /// </summary>
        public static string ToolBarMenu_HorizontalLocationLeft {
            get {
                return ResourceManager.GetString("ToolBarMenu_HorizontalLocationLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 右寄せ 的本地化字符串。
        /// </summary>
        public static string ToolBarMenu_HorizontalLocationRight {
            get {
                return ResourceManager.GetString("ToolBarMenu_HorizontalLocationRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上下の表示位置(_H) 的本地化字符串。
        /// </summary>
        public static string ToolBarMenu_VerticalLocation {
            get {
                return ResourceManager.GetString("ToolBarMenu_VerticalLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下段 的本地化字符串。
        /// </summary>
        public static string ToolBarMenu_VerticalLocationBottom {
            get {
                return ResourceManager.GetString("ToolBarMenu_VerticalLocationBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中段 的本地化字符串。
        /// </summary>
        public static string ToolBarMenu_VerticalLocationMiddle {
            get {
                return ResourceManager.GetString("ToolBarMenu_VerticalLocationMiddle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上段 的本地化字符串。
        /// </summary>
        public static string ToolBarMenu_VerticalLocationTop {
            get {
                return ResourceManager.GetString("ToolBarMenu_VerticalLocationTop", resourceCulture);
            }
        }
    }
}
