//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CeVIO.TalkAnalyzeControl.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CeVIO.TalkAnalyzeControl.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string AccentButtonToolTip {
            get {
                return ResourceManager.GetString("AccentButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Bind {
            get {
                object obj = ResourceManager.GetObject("Bind", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Eraser {
            get {
                object obj = ResourceManager.GetObject("Eraser", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Menu_Audition {
            get {
                return ResourceManager.GetString("Menu_Audition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Menu_AuditionToolTip {
            get {
                return ResourceManager.GetString("Menu_AuditionToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Menu_CombinePhrase {
            get {
                return ResourceManager.GetString("Menu_CombinePhrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Menu_CombinePhraseToolTip {
            get {
                return ResourceManager.GetString("Menu_CombinePhraseToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Menu_DividePhrase {
            get {
                return ResourceManager.GetString("Menu_DividePhrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Menu_DividePhraseToolTip {
            get {
                return ResourceManager.GetString("Menu_DividePhraseToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 グラフ内に音素名を表示(_G) 的本地化字符串。
        /// </summary>
        internal static string Menu_GraphPhonemes {
            get {
                return ResourceManager.GetString("Menu_GraphPhonemes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 棒グラフの上部に音素名を表示します。 的本地化字符串。
        /// </summary>
        internal static string Menu_GraphPhonemesToolTip {
            get {
                return ResourceManager.GetString("Menu_GraphPhonemesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Menu_Mode {
            get {
                return ResourceManager.GetString("Menu_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Menu_Mode_Accent {
            get {
                return ResourceManager.GetString("Menu_Mode_Accent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Menu_Mode_Duration {
            get {
                return ResourceManager.GetString("Menu_Mode_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Menu_Mode_Pitch {
            get {
                return ResourceManager.GetString("Menu_Mode_Pitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Menu_Mode_Volume {
            get {
                return ResourceManager.GetString("Menu_Mode_Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Menu_OverlayDuration {
            get {
                return ResourceManager.GetString("Menu_OverlayDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Menu_OverlayDurationToolTip {
            get {
                return ResourceManager.GetString("Menu_OverlayDurationToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自動試聴で部分再生 的本地化字符串。
        /// </summary>
        internal static string Menu_PartialPlayback {
            get {
                return ResourceManager.GetString("Menu_PartialPlayback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 調整位置の前後のポーズの区間を試聴します。 的本地化字符串。
        /// </summary>
        internal static string Menu_PartialPlaybackToolTip {
            get {
                return ResourceManager.GetString("Menu_PartialPlaybackToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Menu_PhonemeMode {
            get {
                return ResourceManager.GetString("Menu_PhonemeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Menu_PhonemeModeToolTip {
            get {
                return ResourceManager.GetString("Menu_PhonemeModeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Menu_Reset {
            get {
                return ResourceManager.GetString("Menu_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Menu_ResetToolTip {
            get {
                return ResourceManager.GetString("Menu_ResetToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string PitchButtonToolTip {
            get {
                return ResourceManager.GetString("PitchButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string PitchButtonToolTip2 {
            get {
                return ResourceManager.GetString("PitchButtonToolTip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Scissors {
            get {
                object obj = ResourceManager.GetObject("Scissors", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string SpeedButtonToolTip {
            get {
                return ResourceManager.GetString("SpeedButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string VolumeButtonToolTip {
            get {
                return ResourceManager.GetString("VolumeButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string VolumeButtonToolTip2 {
            get {
                return ResourceManager.GetString("VolumeButtonToolTip2", resourceCulture);
            }
        }
    }
}
