//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CeVIO.TalkAnalyzeControl.Properties.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ja_JP {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ja_JP() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CeVIO.TalkAnalyzeControl.Properties.Resources.ja-JP", typeof(ja_JP).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 重音调整
        ///通过拖拽或左键单击指定重音。Ctrl+左键单击恢复初始值。 的本地化字符串。
        /// </summary>
        public static string AccentButtonToolTip {
            get {
                return ResourceManager.GetString("AccentButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] Eraser {
            get {
                object obj = ResourceManager.GetObject("Eraser", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 试听(_A) 的本地化字符串。
        /// </summary>
        public static string Menu_Audition {
            get {
                return ResourceManager.GetString("Menu_Audition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 试听整句台词。
        ///在图中左键单击，可从指定位置开始试听/停止。 的本地化字符串。
        /// </summary>
        public static string Menu_AuditionToolTip {
            get {
                return ResourceManager.GetString("Menu_AuditionToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 组合重音段(_C) 的本地化字符串。
        /// </summary>
        public static string Menu_CombinePhrase {
            get {
                return ResourceManager.GetString("Menu_CombinePhrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将当前重音段与前一段重音段合并。建议在重音调整（ACC）模式下操作。 的本地化字符串。
        /// </summary>
        public static string Menu_CombinePhraseToolTip {
            get {
                return ResourceManager.GetString("Menu_CombinePhraseToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分离重音段(_C) 的本地化字符串。
        /// </summary>
        public static string Menu_DividePhrase {
            get {
                return ResourceManager.GetString("Menu_DividePhrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从当前位置开始分离出一个单独的重音段。建议在重音调整（ACC）模式下操作。 的本地化字符串。
        /// </summary>
        public static string Menu_DividePhraseToolTip {
            get {
                return ResourceManager.GetString("Menu_DividePhraseToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调整模式(_M) 的本地化字符串。
        /// </summary>
        public static string Menu_Mode {
            get {
                return ResourceManager.GetString("Menu_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重音调整(_1) 的本地化字符串。
        /// </summary>
        public static string Menu_Mode_Accent {
            get {
                return ResourceManager.GetString("Menu_Mode_Accent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 音长调整(_4) 的本地化字符串。
        /// </summary>
        public static string Menu_Mode_Duration {
            get {
                return ResourceManager.GetString("Menu_Mode_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 音高调整(_2) 的本地化字符串。
        /// </summary>
        public static string Menu_Mode_Pitch {
            get {
                return ResourceManager.GetString("Menu_Mode_Pitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 音量调整(_3) 的本地化字符串。
        /// </summary>
        public static string Menu_Mode_Volume {
            get {
                return ResourceManager.GetString("Menu_Mode_Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示音长界线(_L) 的本地化字符串。
        /// </summary>
        public static string Menu_OverlayDuration {
            get {
                return ResourceManager.GetString("Menu_OverlayDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消后不显示音长界线。
        ///(音长仍可在上下侧的文字区域通过拖拽或滚动鼠标滚轮调整。) 的本地化字符串。
        /// </summary>
        public static string Menu_OverlayDurationToolTip {
            get {
                return ResourceManager.GetString("Menu_OverlayDurationToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按音素单位调整(_P) 的本地化字符串。
        /// </summary>
        public static string Menu_PhonemeMode {
            get {
                return ResourceManager.GetString("Menu_PhonemeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 切换音素/假名显示模式。
        ///(在假名模式中，使用Alt+拖拽仍可按音素单位调整。) 的本地化字符串。
        /// </summary>
        public static string Menu_PhonemeModeToolTip {
            get {
                return ResourceManager.GetString("Menu_PhonemeModeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 恢复初始值(_R) 的本地化字符串。
        /// </summary>
        public static string Menu_Reset {
            get {
                return ResourceManager.GetString("Menu_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将当前台词恢复到未修改状态。 的本地化字符串。
        /// </summary>
        public static string Menu_ResetToolTip {
            get {
                return ResourceManager.GetString("Menu_ResetToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 音高调整
        ///在图中拖拽调整。按住Shift可水平拖拽。
        ///Ctrl+左键单击恢复初始值。 的本地化字符串。
        /// </summary>
        public static string PitchButtonToolTip {
            get {
                return ResourceManager.GetString("PitchButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 音高与音长调整
        ///在图中拖拽调整。按住Shift可水平拖拽。
        ///Ctrl+左键单击恢复初始值。 的本地化字符串。
        /// </summary>
        public static string PitchButtonToolTip2 {
            get {
                return ResourceManager.GetString("PitchButtonToolTip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 音长调整
        ///在图中拖拽调整。按住Shift可水平拖拽。
        ///Ctrl+左键单击恢复初始值。 的本地化字符串。
        /// </summary>
        public static string SpeedButtonToolTip {
            get {
                return ResourceManager.GetString("SpeedButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 音量调整
        ///在图中拖拽调整。按住Shift可水平拖拽。
        ///Ctrl+左键单击恢复初始值。 的本地化字符串。
        /// </summary>
        public static string VolumeButtonToolTip {
            get {
                return ResourceManager.GetString("VolumeButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 音量与音长调整
        ///在图中拖拽调整。按住Shift可水平拖拽。
        ///Ctrl+左键单击恢复初始值。 的本地化字符串。
        /// </summary>
        public static string VolumeButtonToolTip2 {
            get {
                return ResourceManager.GetString("VolumeButtonToolTip2", resourceCulture);
            }
        }
    }
}
