//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CeVIO.TalkAnalyzeControl.Properties.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class zh_CN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal zh_CN() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CeVIO.TalkAnalyzeControl.Properties.Resources.zh-CN", typeof(zh_CN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 アクセントを調整
        ///ドラッグまたは左クリックでアクセント指定。Ctrl+左クリックでリセット。 的本地化字符串。
        /// </summary>
        public static string AccentButtonToolTip {
            get {
                return ResourceManager.GetString("AccentButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] Eraser {
            get {
                object obj = ResourceManager.GetObject("Eraser", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 試聴(_A) 的本地化字符串。
        /// </summary>
        public static string Menu_Audition {
            get {
                return ResourceManager.GetString("Menu_Audition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 このセリフを先頭から試聴します。
        ///グラフを左クリックして指定位置から試聴／停止も可能。 的本地化字符串。
        /// </summary>
        public static string Menu_AuditionToolTip {
            get {
                return ResourceManager.GetString("Menu_AuditionToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 調整モード(_M) 的本地化字符串。
        /// </summary>
        public static string Menu_Mode {
            get {
                return ResourceManager.GetString("Menu_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 アクセントを調整(_1) 的本地化字符串。
        /// </summary>
        public static string Menu_Mode_Accent {
            get {
                return ResourceManager.GetString("Menu_Mode_Accent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 音の長さを調整(_4) 的本地化字符串。
        /// </summary>
        public static string Menu_Mode_Duration {
            get {
                return ResourceManager.GetString("Menu_Mode_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 音の高さを調整(_2) 的本地化字符串。
        /// </summary>
        public static string Menu_Mode_Pitch {
            get {
                return ResourceManager.GetString("Menu_Mode_Pitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 音の大きさを調整(_3) 的本地化字符串。
        /// </summary>
        public static string Menu_Mode_Volume {
            get {
                return ResourceManager.GetString("Menu_Mode_Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 長さのラインを重ねて表示(_L) 的本地化字符串。
        /// </summary>
        public static string Menu_OverlayDuration {
            get {
                return ResourceManager.GetString("Menu_OverlayDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 オフでラインを消します。
        ///(長さは上下の文字エリアでも、ドラッグやマウスホイールで調整可能。) 的本地化字符串。
        /// </summary>
        public static string Menu_OverlayDurationToolTip {
            get {
                return ResourceManager.GetString("Menu_OverlayDurationToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 音素単位で調整(_P) 的本地化字符串。
        /// </summary>
        public static string Menu_PhonemeMode {
            get {
                return ResourceManager.GetString("Menu_PhonemeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 オフでカナ表示。
        ///(カナ表示中も、Alt+ドラッグで音素単位の調整可能。) 的本地化字符串。
        /// </summary>
        public static string Menu_PhonemeModeToolTip {
            get {
                return ResourceManager.GetString("Menu_PhonemeModeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 初期値に戻す(_R) 的本地化字符串。
        /// </summary>
        public static string Menu_Reset {
            get {
                return ResourceManager.GetString("Menu_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 このセリフを初期状態に戻します。 的本地化字符串。
        /// </summary>
        public static string Menu_ResetToolTip {
            get {
                return ResourceManager.GetString("Menu_ResetToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 音の高さを調整
        ///グラフをドラッグして調整。Shift+ドラッグで水平。
        ///Ctrl+左クリックでリセット。 的本地化字符串。
        /// </summary>
        public static string PitchButtonToolTip {
            get {
                return ResourceManager.GetString("PitchButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 音の高さと長さを調整
        ///グラフをドラッグして調整。Shift+ドラッグで水平。
        ///Ctrl+左クリックでリセット。 的本地化字符串。
        /// </summary>
        public static string PitchButtonToolTip2 {
            get {
                return ResourceManager.GetString("PitchButtonToolTip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 音の長さを調整
        ///グラフをドラッグして調整。Shift+ドラッグで水平。
        ///Ctrl+左クリックでリセット。 的本地化字符串。
        /// </summary>
        public static string SpeedButtonToolTip {
            get {
                return ResourceManager.GetString("SpeedButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 音の大きさを調整
        ///グラフをドラッグして調整。Shift+ドラッグで水平。
        ///Ctrl+左クリックでリセット。 的本地化字符串。
        /// </summary>
        public static string VolumeButtonToolTip {
            get {
                return ResourceManager.GetString("VolumeButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 音の大きさと長さを調整
        ///グラフをドラッグして調整。Shift+ドラッグで水平。
        ///Ctrl+左クリックでリセット。 的本地化字符串。
        /// </summary>
        public static string VolumeButtonToolTip2 {
            get {
                return ResourceManager.GetString("VolumeButtonToolTip2", resourceCulture);
            }
        }
    }
}
