//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CeVIO.SongEditorControl.Properties.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ja_JP {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ja_JP() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CeVIO.SongEditorControl.Properties.Resources.ja-JP", typeof(ja_JP).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 已修正音符位置。 的本地化字符串。
        /// </summary>
        public static string AdjustNotesLength {
            get {
                return ResourceManager.GetString("AdjustNotesLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已修正音符长度。 的本地化字符串。
        /// </summary>
        public static string AdjustNotesPosition {
            get {
                return ResourceManager.GetString("AdjustNotesPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已修正音符位置和长度。 的本地化字符串。
        /// </summary>
        public static string AdjustNotesPositionLength {
            get {
                return ResourceManager.GetString("AdjustNotesPositionLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 属性 的本地化字符串。
        /// </summary>
        public static string Attribute {
            get {
                return ResourceManager.GetString("Attribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 试听/停止 [Shift+Space] 的本地化字符串。
        /// </summary>
        public static string Audition {
            get {
                return ResourceManager.GetString("Audition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已固定的音轨无法试听，请直接播放。 的本地化字符串。
        /// </summary>
        public static string AuditionDisabledMessage {
            get {
                return ResourceManager.GetString("AuditionDisabledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动试听 的本地化字符串。
        /// </summary>
        public static string AutoAudition {
            get {
                return ResourceManager.GetString("AutoAudition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拍子 的本地化字符串。
        /// </summary>
        public static string Beat {
            get {
                return ResourceManager.GetString("Beat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑拍子后，将对所有歌唱音轨的调号的位置进行修正。 的本地化字符串。
        /// </summary>
        public static string BeatChangeConfirmationDialogText {
            get {
                return ResourceManager.GetString("BeatChangeConfirmationDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调号位置修正确认 的本地化字符串。
        /// </summary>
        public static string BeatChangeConfirmationDialogTitle {
            get {
                return ResourceManager.GetString("BeatChangeConfirmationDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拍子属性 的本地化字符串。
        /// </summary>
        public static string BeatDialogTitle {
            get {
                return ResourceManager.GetString("BeatDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拍子 的本地化字符串。
        /// </summary>
        public static string BeatNumber {
            get {
                return ResourceManager.GetString("BeatNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拍子行(全音轨共用)
        ///双击编辑。拖拽移动。用画笔工具双击空白处添加。 的本地化字符串。
        /// </summary>
        public static string BeatRowToolTip {
            get {
                return ResourceManager.GetString("BeatRowToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 呼吸 的本地化字符串。
        /// </summary>
        public static string Breath {
            get {
                return ResourceManager.GetString("Breath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在这里喘气。 的本地化字符串。
        /// </summary>
        public static string BreathToolTip {
            get {
                return ResourceManager.GetString("BreathToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数计算中 的本地化字符串。
        /// </summary>
        public static string CalculatingParameters {
            get {
                return ResourceManager.GetString("CalculatingParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 轨道 的本地化字符串。
        /// </summary>
        public static string ChannelNumber {
            get {
                return ResourceManager.GetString("ChannelNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 长度 的本地化字符串。
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 强弱记号 的本地化字符串。
        /// </summary>
        public static string Dynamics {
            get {
                return ResourceManager.GetString("Dynamics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 强弱记号属性 的本地化字符串。
        /// </summary>
        public static string DynamicsDialogTitle {
            get {
                return ResourceManager.GetString("DynamicsDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 强弱记号行
        ///双击编辑。拖拽移动。用画笔工具双击空白处添加。 的本地化字符串。
        /// </summary>
        public static string DynamicsRowToolTip {
            get {
                return ResourceManager.GetString("DynamicsRowToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] Eraser {
            get {
                object obj = ResourceManager.GetObject("Eraser", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] Eraser2 {
            get {
                object obj = ResourceManager.GetObject("Eraser2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 消除短空白 的本地化字符串。
        /// </summary>
        public static string FillSpacesDialogTitle {
            get {
                return ResourceManager.GetString("FillSpacesDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 要去除的空白的最大长度 的本地化字符串。
        /// </summary>
        public static string FillSpacesDuration {
            get {
                return ResourceManager.GetString("FillSpacesDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法读取声源 的本地化字符串。
        /// </summary>
        public static string InvalidVoice {
            get {
                return ResourceManager.GetString("InvalidVoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调号(Key) 的本地化字符串。
        /// </summary>
        public static string Key {
            get {
                return ResourceManager.GetString("Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调号属性 的本地化字符串。
        /// </summary>
        public static string KeyDialogTitle {
            get {
                return ResourceManager.GetString("KeyDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调号(Key)行
        ///双击编辑。拖动移动。用画笔工具双击空白处添加。 的本地化字符串。
        /// </summary>
        public static string KeyRowToolTip {
            get {
                return ResourceManager.GetString("KeyRowToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 歌词 的本地化字符串。
        /// </summary>
        public static string Lyric {
            get {
                return ResourceManager.GetString("Lyric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从开头的音符开始设置歌词。(最大 的本地化字符串。
        /// </summary>
        public static string LyricDialogCaption1 {
            get {
                return ResourceManager.GetString("LyricDialogCaption1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 音符) 的本地化字符串。
        /// </summary>
        public static string LyricDialogCaption2 {
            get {
                return ResourceManager.GetString("LyricDialogCaption2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从选中的音符开始设置歌词。(最大 的本地化字符串。
        /// </summary>
        public static string LyricDialogCaption3 {
            get {
                return ResourceManager.GetString("LyricDialogCaption3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按空格划分并分配每个音符的歌词。 的本地化字符串。
        /// </summary>
        public static string LyricDialogCaption4 {
            get {
                return ResourceManager.GetString("LyricDialogCaption4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包含不能发音的字符。
        ///请用全角假名输入歌词。
        ///仍要使用这些歌词吗？ 的本地化字符串。
        /// </summary>
        public static string LyricDialogError {
            get {
                return ResourceManager.GetString("LyricDialogError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 长段歌词输入 的本地化字符串。
        /// </summary>
        public static string LyricDialogTitle {
            get {
                return ResourceManager.GetString("LyricDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包含不能发音的字符。
        ///请用全角假名输入歌词。 的本地化字符串。
        /// </summary>
        public static string LyricError {
            get {
                return ResourceManager.GetString("LyricError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按音素输入歌词(_M) 的本地化字符串。
        /// </summary>
        public static string LyricTextBoxMenuPhonetic {
            get {
                return ResourceManager.GetString("LyricTextBoxMenuPhonetic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用音素记号输入歌词。 的本地化字符串。
        /// </summary>
        public static string LyricTextBoxMenuPhoneticToolTip {
            get {
                return ResourceManager.GetString("LyricTextBoxMenuPhoneticToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小节 的本地化字符串。
        /// </summary>
        public static string MeasureNumber {
            get {
                return ResourceManager.GetString("MeasureNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小节行
        ///双击播放／停止。
        ///（各行通用）左键单击移动光标。
        ///（各行通用）水平拖动滚动。垂直拖动缩放。 的本地化字符串。
        /// </summary>
        public static string MeasureRowToolTip {
            get {
                return ResourceManager.GetString("MeasureRowToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制(_C) 的本地化字符串。
        /// </summary>
        public static string MenuCopy {
            get {
                return ResourceManager.GetString("MenuCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 剪切(_T) 的本地化字符串。
        /// </summary>
        public static string MenuCut {
            get {
                return ResourceManager.GetString("MenuCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除(_D) 的本地化字符串。
        /// </summary>
        public static string MenuDelete {
            get {
                return ResourceManager.GetString("MenuDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 粘贴(_P) 的本地化字符串。
        /// </summary>
        public static string MenuPaste {
            get {
                return ResourceManager.GetString("MenuPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全选(_A) 的本地化字符串。
        /// </summary>
        public static string MenuSelectAll {
            get {
                return ResourceManager.GetString("MenuSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 撤销(_U) 的本地化字符串。
        /// </summary>
        public static string MenuUndo {
            get {
                return ResourceManager.GetString("MenuUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此文件在1个音轨中包含所有的Channel。
        ///要将Channel分割到不同的音轨中吗？ 的本地化字符串。
        /// </summary>
        public static string MidiImportChannelSelect {
            get {
                return ResourceManager.GetString("MidiImportChannelSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择要读取的音轨。(最大 的本地化字符串。
        /// </summary>
        public static string MidiImportDialogCaption1 {
            get {
                return ResourceManager.GetString("MidiImportDialogCaption1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 音轨) 的本地化字符串。
        /// </summary>
        public static string MidiImportDialogCaption2 {
            get {
                return ResourceManager.GetString("MidiImportDialogCaption2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 曲速( 的本地化字符串。
        /// </summary>
        public static string MidiImportDialogCaptionB1 {
            get {
                return ResourceManager.GetString("MidiImportDialogCaptionB1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 )和拍子( 的本地化字符串。
        /// </summary>
        public static string MidiImportDialogCaptionB2 {
            get {
                return ResourceManager.GetString("MidiImportDialogCaptionB2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 )也一并读取 的本地化字符串。
        /// </summary>
        public static string MidiImportDialogCaptionB3 {
            get {
                return ResourceManager.GetString("MidiImportDialogCaptionB3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取曲速和拍子 的本地化字符串。
        /// </summary>
        public static string MidiImportDialogCheckBoxText {
            get {
                return ResourceManager.GetString("MidiImportDialogCheckBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 音符 的本地化字符串。
        /// </summary>
        public static string MidiImportDialogNotes {
            get {
                return ResourceManager.GetString("MidiImportDialogNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择 的本地化字符串。
        /// </summary>
        public static string MidiImportDialogSelect {
            get {
                return ResourceManager.GetString("MidiImportDialogSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入MIDI 的本地化字符串。
        /// </summary>
        public static string MidiImportDialogTitle {
            get {
                return ResourceManager.GetString("MidiImportDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持MIDI格式2。 的本地化字符串。
        /// </summary>
        public static string MidiImportFormatError {
            get {
                return ResourceManager.GetString("MidiImportFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件头读取失败。 的本地化字符串。
        /// </summary>
        public static string MidiImportHeaderError {
            get {
                return ResourceManager.GetString("MidiImportHeaderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有音轨。 的本地化字符串。
        /// </summary>
        public static string MidiImportNoTrackError {
            get {
                return ResourceManager.GetString("MidiImportNoTrackError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持实际时间单位（支持Tick单位）。 的本地化字符串。
        /// </summary>
        public static string MidiImportTimeBaseError {
            get {
                return ResourceManager.GetString("MidiImportTimeBaseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 音轨读取失败。 的本地化字符串。
        /// </summary>
        public static string MidiImportTrackError {
            get {
                return ResourceManager.GetString("MidiImportTrackError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 要读取曲速和拍子信息吗？
        ///（将作用于所有音轨） 的本地化字符串。
        /// </summary>
        public static string MusicXmlImportConfirmationText {
            get {
                return ResourceManager.GetString("MusicXmlImportConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入MusicXML 的本地化字符串。
        /// </summary>
        public static string MusicXmlImportDialogTitle {
            get {
                return ResourceManager.GetString("MusicXmlImportDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 音符属性 的本地化字符串。
        /// </summary>
        public static string NoteDialogTitle {
            get {
                return ResourceManager.GetString("NoteDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1音符1字符 的本地化字符串。
        /// </summary>
        public static string OneNoteOneMora {
            get {
                return ResourceManager.GetString("OneNoteOneMora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 每个字符对应一个音符。
        ///只有当连续出现小写（半角）字符时才会把两个字符划分到一个音符。 的本地化字符串。
        /// </summary>
        public static string OneNoteOneMoraToolTip {
            get {
                return ResourceManager.GetString("OneNoteOneMoraToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 播放中无法计算参数 的本地化字符串。
        /// </summary>
        public static string ParametersCannotBeCalculated {
            get {
                return ResourceManager.GetString("ParametersCannotBeCalculated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 音素 的本地化字符串。
        /// </summary>
        public static string Phonemes {
            get {
                return ResourceManager.GetString("Phonemes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 英语 音素面板 的本地化字符串。
        /// </summary>
        public static string PhoneticWindowTitleEn {
            get {
                return ResourceManager.GetString("PhoneticWindowTitleEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日语 音素面板 的本地化字符串。
        /// </summary>
        public static string PhoneticWindowTitleJa {
            get {
                return ResourceManager.GetString("PhoneticWindowTitleJa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 长段歌词输入(_I)... 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_EnterLyricsCollectively {
            get {
                return ResourceManager.GetString("PianoRollMenu_EnterLyricsCollectively", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从选中的第一个音符的位置开始输入歌词。 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_EnterLyricsCollectivelyToolTip {
            get {
                return ResourceManager.GetString("PianoRollMenu_EnterLyricsCollectivelyToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按音素输入歌词(_P) 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_EnterLyricsWithPhoneme {
            get {
                return ResourceManager.GetString("PianoRollMenu_EnterLyricsWithPhoneme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用音素记号输入歌词。 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_EnterLyricsWithPhonemeToolTip {
            get {
                return ResourceManager.GetString("PianoRollMenu_EnterLyricsWithPhonemeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 消除短空白(_F)... 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_FillSpaces {
            get {
                return ResourceManager.GetString("PianoRollMenu_FillSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将选中的音符区间中的长音符进行扩展以填满其中的间隙。 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_FillSpacesToolTip {
            get {
                return ResourceManager.GetString("PianoRollMenu_FillSpacesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数调整(_M) 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_Mode {
            get {
                return ResourceManager.GetString("PianoRollMenu_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 乐谱编辑(_1) 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_Mode_Normal {
            get {
                return ResourceManager.GetString("PianoRollMenu_Mode_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 切换到乐谱编辑界面。 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_Mode_NormalToolTip {
            get {
                return ResourceManager.GetString("PianoRollMenu_Mode_NormalToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 音高(PIT)调整(_4) 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_Mode_Pitch {
            get {
                return ResourceManager.GetString("PianoRollMenu_Mode_Pitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 切换到音高调整界面。
        ///当与颤音振幅/周期重叠显示时，会额外显示颤音的音高。 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_Mode_PitchToolTip {
            get {
                return ResourceManager.GetString("PianoRollMenu_Mode_PitchToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间(TMG)调整(_2) 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_Mode_Timing {
            get {
                return ResourceManager.GetString("PianoRollMenu_Mode_Timing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 切换到时间调整界面。可调整每个音素的长短。 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_Mode_TimingToolTip {
            get {
                return ResourceManager.GetString("PianoRollMenu_Mode_TimingToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 颤音振幅(VIA)调整(_5) 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_Mode_VibratoAmplitude {
            get {
                return ResourceManager.GetString("PianoRollMenu_Mode_VibratoAmplitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 切换到颤音振幅调整界面。 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_Mode_VibratoAmplitudeToolTip {
            get {
                return ResourceManager.GetString("PianoRollMenu_Mode_VibratoAmplitudeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 颤音周期(VIF)调整(_6) 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_Mode_VibratoFrequency {
            get {
                return ResourceManager.GetString("PianoRollMenu_Mode_VibratoFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 切换到颤音周期调整界面。 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_Mode_VibratoFrequencyToolTip {
            get {
                return ResourceManager.GetString("PianoRollMenu_Mode_VibratoFrequencyToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 音量(VOL)调整(_3) 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_Mode_Volume {
            get {
                return ResourceManager.GetString("PianoRollMenu_Mode_Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 切换到音量调整界面。可调整每个时刻的音量。 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_Mode_VolumeToolTip {
            get {
                return ResourceManager.GetString("PianoRollMenu_Mode_VolumeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 其他音轨的音符(_P) 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_NotesOfOtherTracks {
            get {
                return ResourceManager.GetString("PianoRollMenu_NotesOfOtherTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在乐谱编辑界面也显示别的音轨中的音符。
        ///（不会显示已静音的音轨的音符。） 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_NotesOfOtherTracksToolTip {
            get {
                return ResourceManager.GetString("PianoRollMenu_NotesOfOtherTracksToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重叠显示(_P) 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_Overlay {
            get {
                return ResourceManager.GetString("PianoRollMenu_Overlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示音高(_4) 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_OverLay_Pitch {
            get {
                return ResourceManager.GetString("PianoRollMenu_OverLay_Pitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重叠显示音高（PIT）。重叠显示时额外显示颤音。 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_OverLay_PitchToolTip {
            get {
                return ResourceManager.GetString("PianoRollMenu_OverLay_PitchToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示时间(_2) 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_OverLay_Timing {
            get {
                return ResourceManager.GetString("PianoRollMenu_OverLay_Timing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重叠显示时间（TMG）。 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_OverLay_TimingToolTip {
            get {
                return ResourceManager.GetString("PianoRollMenu_OverLay_TimingToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示颤音振幅(_5) 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_OverLay_VibratoAmplitude {
            get {
                return ResourceManager.GetString("PianoRollMenu_OverLay_VibratoAmplitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重叠显示颤音振幅（VIA）。 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_OverLay_VibratoAmplitudeToolTip {
            get {
                return ResourceManager.GetString("PianoRollMenu_OverLay_VibratoAmplitudeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示颤音周期(_6) 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_OverLay_VibratoFrequency {
            get {
                return ResourceManager.GetString("PianoRollMenu_OverLay_VibratoFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重叠显示颤音周期（VIF）。 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_OverLay_VibratoFrequencyToolTip {
            get {
                return ResourceManager.GetString("PianoRollMenu_OverLay_VibratoFrequencyToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示音量(_3) 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_OverLay_Volume {
            get {
                return ResourceManager.GetString("PianoRollMenu_OverLay_Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重叠显示音量（VOL）。 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_OverLay_VolumeToolTip {
            get {
                return ResourceManager.GetString("PianoRollMenu_OverLay_VolumeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 属性(_R)... 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_Properties {
            get {
                return ResourceManager.GetString("PianoRollMenu_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置音符的详细属性，包括呼吸和连音。
        ///选中多个音符可同时设置。数值可用+-来指定相对值。 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_PropertiesToolTip {
            get {
                return ResourceManager.GetString("PianoRollMenu_PropertiesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑曲速、拍子、调号。 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_PropertiesToolTip2 {
            get {
                return ResourceManager.GetString("PianoRollMenu_PropertiesToolTip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 量化(_Q) 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_Quantize {
            get {
                return ResourceManager.GetString("PianoRollMenu_Quantize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1/16(3连音) 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_Quantize_Triplet16 {
            get {
                return ResourceManager.GetString("PianoRollMenu_Quantize_Triplet16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1/2(3连音) 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_Quantize_Triplet2 {
            get {
                return ResourceManager.GetString("PianoRollMenu_Quantize_Triplet2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1/4(3连音) 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_Quantize_Triplet4 {
            get {
                return ResourceManager.GetString("PianoRollMenu_Quantize_Triplet4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1/8(3连音) 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_Quantize_Triplet8 {
            get {
                return ResourceManager.GetString("PianoRollMenu_Quantize_Triplet8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 范围选择工具(_2) 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_Tool_BulkSelect {
            get {
                return ResourceManager.GetString("PianoRollMenu_Tool_BulkSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 橡皮擦工具(_5) 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_Tool_Eraser {
            get {
                return ResourceManager.GetString("PianoRollMenu_Tool_Eraser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 直线工具(_4) 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_Tool_Line {
            get {
                return ResourceManager.GetString("PianoRollMenu_Tool_Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 画笔工具(_3) 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_Tool_Pen {
            get {
                return ResourceManager.GetString("PianoRollMenu_Tool_Pen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择工具(_1) 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_Tool_Select {
            get {
                return ResourceManager.GetString("PianoRollMenu_Tool_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消颤音(_V) 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_VibratoDisable {
            get {
                return ResourceManager.GetString("PianoRollMenu_VibratoDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将本音轨的所有颤音无效化。 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_VibratoDisableToolTip {
            get {
                return ResourceManager.GetString("PianoRollMenu_VibratoDisableToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表示(_V) 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_View {
            get {
                return ResourceManager.GetString("PianoRollMenu_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拍子网格线(_G) 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_View_BeatLine {
            get {
                return ResourceManager.GetString("PianoRollMenu_View_BeatLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示拍子行的网格线。 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_View_BeatLineToolTip {
            get {
                return ResourceManager.GetString("PianoRollMenu_View_BeatLineToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拍子行(_B) 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_View_BeatRow {
            get {
                return ResourceManager.GetString("PianoRollMenu_View_BeatRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示拍子（BEAT）行的标尺。 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_View_BeatRowToolTip {
            get {
                return ResourceManager.GetString("PianoRollMenu_View_BeatRowToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 强弱记号行(_D) 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_View_DynamicsRow {
            get {
                return ResourceManager.GetString("PianoRollMenu_View_DynamicsRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示强弱记号（DYNAMICS）行的标尺。 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_View_DynamicsRowToolTip {
            get {
                return ResourceManager.GetString("PianoRollMenu_View_DynamicsRowToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 光标指示器(_C) 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_View_GuideLine {
            get {
                return ResourceManager.GetString("PianoRollMenu_View_GuideLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 高亮显示离鼠标最近的量化线。 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_View_GuideLineToolTip {
            get {
                return ResourceManager.GetString("PianoRollMenu_View_GuideLineToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调号行(_K) 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_View_KeyRow {
            get {
                return ResourceManager.GetString("PianoRollMenu_View_KeyRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示调号（KEY）行的标尺。 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_View_KeyRowToolTip {
            get {
                return ResourceManager.GetString("PianoRollMenu_View_KeyRowToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 量化线(_Q) 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_View_QuantizeLine {
            get {
                return ResourceManager.GetString("PianoRollMenu_View_QuantizeLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示最小量化单位的网格线。 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_View_QuantizeLineToolTip {
            get {
                return ResourceManager.GetString("PianoRollMenu_View_QuantizeLineToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 曲速行(_T) 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_View_TempoRow {
            get {
                return ResourceManager.GetString("PianoRollMenu_View_TempoRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示曲速（TEMPO）行的标尺。 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_View_TempoRowToolTip {
            get {
                return ResourceManager.GetString("PianoRollMenu_View_TempoRowToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在调整界面也显示网格线(_V) 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_View_TuningLine {
            get {
                return ResourceManager.GetString("PianoRollMenu_View_TuningLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在调整界面也显示拍子或是量化的网格线。 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_View_TuningLineToolTip {
            get {
                return ResourceManager.GetString("PianoRollMenu_View_TuningLineToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 音高 的本地化字符串。
        /// </summary>
        public static string Pitch {
            get {
                return ResourceManager.GetString("Pitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 位置 的本地化字符串。
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连音开始 的本地化字符串。
        /// </summary>
        public static string SlurBegin {
            get {
                return ResourceManager.GetString("SlurBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连音结束 的本地化字符串。
        /// </summary>
        public static string SlurEnd {
            get {
                return ResourceManager.GetString("SlurEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从连音开始标记到结束标记为止流畅地演唱。
        ///在乐谱编辑界面选中多个连续音符并按[Ctrl+R]也可以设置。 的本地化字符串。
        /// </summary>
        public static string SlurToolTip {
            get {
                return ResourceManager.GetString("SlurToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 音 的本地化字符串。
        /// </summary>
        public static string Sound {
            get {
                return ResourceManager.GetString("Sound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 空格分隔 的本地化字符串。
        /// </summary>
        public static string SpaceDelimited {
            get {
                return ResourceManager.GetString("SpaceDelimited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按空格将歌词分配到音符。
        ///此时一个音符可能包含2个及以上的字符。 的本地化字符串。
        /// </summary>
        public static string SpaceDelimitedToolTip {
            get {
                return ResourceManager.GetString("SpaceDelimitedToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调整分隔位置(Ctrl+左键单击恢复默认) 的本地化字符串。
        /// </summary>
        public static string SplitterToolTip {
            get {
                return ResourceManager.GetString("SplitterToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 曲速 的本地化字符串。
        /// </summary>
        public static string Tempo {
            get {
                return ResourceManager.GetString("Tempo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 曲速属性 的本地化字符串。
        /// </summary>
        public static string TempoDialogTitle {
            get {
                return ResourceManager.GetString("TempoDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 曲速行(全音轨共用)
        ///双击编辑。拖拽移动。用画笔工具双击空白处添加。 的本地化字符串。
        /// </summary>
        public static string TempoRowToolTip {
            get {
                return ResourceManager.GetString("TempoRowToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tick 的本地化字符串。
        /// </summary>
        public static string Tick {
            get {
                return ResourceManager.GetString("Tick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 音轨名 的本地化字符串。
        /// </summary>
        public static string TrackName {
            get {
                return ResourceManager.GetString("TrackName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消颤音 的本地化字符串。
        /// </summary>
        public static string VibratoDisabled {
            get {
                return ResourceManager.GetString("VibratoDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 音色 的本地化字符串。
        /// </summary>
        public static string VoiceAlpha {
            get {
                return ResourceManager.GetString("VoiceAlpha", resourceCulture);
            }
        }
    }
}
