//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CeVIO.SongEditorControl.Properties.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class zh_CN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal zh_CN() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CeVIO.SongEditorControl.Properties.Resources.zh-CN", typeof(zh_CN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 音符の位置を補正しました。 的本地化字符串。
        /// </summary>
        public static string AdjustNotesLength {
            get {
                return ResourceManager.GetString("AdjustNotesLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 音符の長さを補正しました。 的本地化字符串。
        /// </summary>
        public static string AdjustNotesPosition {
            get {
                return ResourceManager.GetString("AdjustNotesPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 音符の位置と長さを補正しました。 的本地化字符串。
        /// </summary>
        public static string AdjustNotesPositionLength {
            get {
                return ResourceManager.GetString("AdjustNotesPositionLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 属性 的本地化字符串。
        /// </summary>
        public static string Attribute {
            get {
                return ResourceManager.GetString("Attribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 試聴/停止 [Shift+Space] 的本地化字符串。
        /// </summary>
        public static string Audition {
            get {
                return ResourceManager.GetString("Audition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 固定トラックは試聴できません。再生してください。 的本地化字符串。
        /// </summary>
        public static string AuditionDisabledMessage {
            get {
                return ResourceManager.GetString("AuditionDisabledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自動試聴 的本地化字符串。
        /// </summary>
        public static string AutoAudition {
            get {
                return ResourceManager.GetString("AutoAudition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拍子 的本地化字符串。
        /// </summary>
        public static string Beat {
            get {
                return ResourceManager.GetString("Beat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拍子を編集すると、全ソングトラックの調号の位置が補正されます。 的本地化字符串。
        /// </summary>
        public static string BeatChangeConfirmationDialogText {
            get {
                return ResourceManager.GetString("BeatChangeConfirmationDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 調号の位置補正の確認 的本地化字符串。
        /// </summary>
        public static string BeatChangeConfirmationDialogTitle {
            get {
                return ResourceManager.GetString("BeatChangeConfirmationDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拍子のプロパティ 的本地化字符串。
        /// </summary>
        public static string BeatDialogTitle {
            get {
                return ResourceManager.GetString("BeatDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拍子 的本地化字符串。
        /// </summary>
        public static string BeatNumber {
            get {
                return ResourceManager.GetString("BeatNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拍子行(全トラック共通)
        ///ダブルクリックで編集。ドラッグで移動。追加はペンでダブルクリック。 的本地化字符串。
        /// </summary>
        public static string BeatRowToolTip {
            get {
                return ResourceManager.GetString("BeatRowToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ブレス 的本地化字符串。
        /// </summary>
        public static string Breath {
            get {
                return ResourceManager.GetString("Breath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 息継ぎをします。 的本地化字符串。
        /// </summary>
        public static string BreathToolTip {
            get {
                return ResourceManager.GetString("BreathToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 パラメータ計算中 的本地化字符串。
        /// </summary>
        public static string CalculatingParameters {
            get {
                return ResourceManager.GetString("CalculatingParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 キャンセル 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 チャンネル 的本地化字符串。
        /// </summary>
        public static string ChannelNumber {
            get {
                return ResourceManager.GetString("ChannelNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 長さ 的本地化字符串。
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 強弱記号 的本地化字符串。
        /// </summary>
        public static string Dynamics {
            get {
                return ResourceManager.GetString("Dynamics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 強弱記号のプロパティ 的本地化字符串。
        /// </summary>
        public static string DynamicsDialogTitle {
            get {
                return ResourceManager.GetString("DynamicsDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 強弱記号行
        ///ダブルクリックで編集。ドラッグで移動。追加はペンでダブルクリック。 的本地化字符串。
        /// </summary>
        public static string DynamicsRowToolTip {
            get {
                return ResourceManager.GetString("DynamicsRowToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] Eraser {
            get {
                object obj = ResourceManager.GetObject("Eraser", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] Eraser2 {
            get {
                object obj = ResourceManager.GetObject("Eraser2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 細かい空白の除去 的本地化字符串。
        /// </summary>
        public static string FillSpacesDialogTitle {
            get {
                return ResourceManager.GetString("FillSpacesDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 除去する空白の長さ 的本地化字符串。
        /// </summary>
        public static string FillSpacesDuration {
            get {
                return ResourceManager.GetString("FillSpacesDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ボイスが読み込まれていません 的本地化字符串。
        /// </summary>
        public static string InvalidVoice {
            get {
                return ResourceManager.GetString("InvalidVoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 調号(キー) 的本地化字符串。
        /// </summary>
        public static string Key {
            get {
                return ResourceManager.GetString("Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 調号のプロパティ 的本地化字符串。
        /// </summary>
        public static string KeyDialogTitle {
            get {
                return ResourceManager.GetString("KeyDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 調号(キー)行
        ///ダブルクリックで編集。ドラッグで移動。追加はペンでダブルクリック。 的本地化字符串。
        /// </summary>
        public static string KeyRowToolTip {
            get {
                return ResourceManager.GetString("KeyRowToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 歌詞 的本地化字符串。
        /// </summary>
        public static string Lyric {
            get {
                return ResourceManager.GetString("Lyric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 先頭の音符から歌詞を設定します。(最大 的本地化字符串。
        /// </summary>
        public static string LyricDialogCaption1 {
            get {
                return ResourceManager.GetString("LyricDialogCaption1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 音符) 的本地化字符串。
        /// </summary>
        public static string LyricDialogCaption2 {
            get {
                return ResourceManager.GetString("LyricDialogCaption2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 選択中の音符から歌詞を設定します。(最大 的本地化字符串。
        /// </summary>
        public static string LyricDialogCaption3 {
            get {
                return ResourceManager.GetString("LyricDialogCaption3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 音符毎にスペースで区切られた文字を割り当てます。 的本地化字符串。
        /// </summary>
        public static string LyricDialogCaption4 {
            get {
                return ResourceManager.GetString("LyricDialogCaption4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 発音できない文字が含まれています。
        ///歌詞は全角かな／全角カナで入力してください。
        ///このまま音符に反映しますか？ 的本地化字符串。
        /// </summary>
        public static string LyricDialogError {
            get {
                return ResourceManager.GetString("LyricDialogError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 歌詞のまとめ入力 的本地化字符串。
        /// </summary>
        public static string LyricDialogTitle {
            get {
                return ResourceManager.GetString("LyricDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 発音できない文字が含まれています。
        ///歌詞は全角かな／全角カナで入力してください。 的本地化字符串。
        /// </summary>
        public static string LyricError {
            get {
                return ResourceManager.GetString("LyricError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 音素で歌詞入力(_M) 的本地化字符串。
        /// </summary>
        public static string LyricTextBoxMenuPhonetic {
            get {
                return ResourceManager.GetString("LyricTextBoxMenuPhonetic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 歌詞を音素記号で入力します。 的本地化字符串。
        /// </summary>
        public static string LyricTextBoxMenuPhoneticToolTip {
            get {
                return ResourceManager.GetString("LyricTextBoxMenuPhoneticToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小節 的本地化字符串。
        /// </summary>
        public static string MeasureNumber {
            get {
                return ResourceManager.GetString("MeasureNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小節行
        ///ダブルクリックで再生／停止。
        ///（各行共通）左クリックでポジションカーソル移動。
        ///（各行共通）水平ドラッグで簡易スクロール。垂直ドラッグで簡易ズーム。 的本地化字符串。
        /// </summary>
        public static string MeasureRowToolTip {
            get {
                return ResourceManager.GetString("MeasureRowToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 コピー(_C) 的本地化字符串。
        /// </summary>
        public static string MenuCopy {
            get {
                return ResourceManager.GetString("MenuCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 切り取り(_T) 的本地化字符串。
        /// </summary>
        public static string MenuCut {
            get {
                return ResourceManager.GetString("MenuCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 削除(_D) 的本地化字符串。
        /// </summary>
        public static string MenuDelete {
            get {
                return ResourceManager.GetString("MenuDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 貼り付け(_P) 的本地化字符串。
        /// </summary>
        public static string MenuPaste {
            get {
                return ResourceManager.GetString("MenuPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 すべて選択(_A) 的本地化字符串。
        /// </summary>
        public static string MenuSelectAll {
            get {
                return ResourceManager.GetString("MenuSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 元に戻す(_U) 的本地化字符串。
        /// </summary>
        public static string MenuUndo {
            get {
                return ResourceManager.GetString("MenuUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1トラックに全チャンネルが含まれるファイルです。
        ///チャンネルをトラックに割り当てますか？ 的本地化字符串。
        /// </summary>
        public static string MidiImportChannelSelect {
            get {
                return ResourceManager.GetString("MidiImportChannelSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 読み込むトラックを選択します。(最大 的本地化字符串。
        /// </summary>
        public static string MidiImportDialogCaption1 {
            get {
                return ResourceManager.GetString("MidiImportDialogCaption1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 トラック) 的本地化字符串。
        /// </summary>
        public static string MidiImportDialogCaption2 {
            get {
                return ResourceManager.GetString("MidiImportDialogCaption2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 テンポ( 的本地化字符串。
        /// </summary>
        public static string MidiImportDialogCaptionB1 {
            get {
                return ResourceManager.GetString("MidiImportDialogCaptionB1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 )と拍子( 的本地化字符串。
        /// </summary>
        public static string MidiImportDialogCaptionB2 {
            get {
                return ResourceManager.GetString("MidiImportDialogCaptionB2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 )も読み込む 的本地化字符串。
        /// </summary>
        public static string MidiImportDialogCaptionB3 {
            get {
                return ResourceManager.GetString("MidiImportDialogCaptionB3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 テンポと拍子を読み込む 的本地化字符串。
        /// </summary>
        public static string MidiImportDialogCheckBoxText {
            get {
                return ResourceManager.GetString("MidiImportDialogCheckBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 音符 的本地化字符串。
        /// </summary>
        public static string MidiImportDialogNotes {
            get {
                return ResourceManager.GetString("MidiImportDialogNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 選択 的本地化字符串。
        /// </summary>
        public static string MidiImportDialogSelect {
            get {
                return ResourceManager.GetString("MidiImportDialogSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MIDIインポート 的本地化字符串。
        /// </summary>
        public static string MidiImportDialogTitle {
            get {
                return ResourceManager.GetString("MidiImportDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 フォーマット2は非対応です。 的本地化字符串。
        /// </summary>
        public static string MidiImportFormatError {
            get {
                return ResourceManager.GetString("MidiImportFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ヘッダーの読み込みに失敗しました。 的本地化字符串。
        /// </summary>
        public static string MidiImportHeaderError {
            get {
                return ResourceManager.GetString("MidiImportHeaderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 トラックがありません。 的本地化字符串。
        /// </summary>
        public static string MidiImportNoTrackError {
            get {
                return ResourceManager.GetString("MidiImportNoTrackError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 実時間単位は非対応です（ティック指定に対応）。 的本地化字符串。
        /// </summary>
        public static string MidiImportTimeBaseError {
            get {
                return ResourceManager.GetString("MidiImportTimeBaseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 トラックの読み込みに失敗しました。 的本地化字符串。
        /// </summary>
        public static string MidiImportTrackError {
            get {
                return ResourceManager.GetString("MidiImportTrackError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 テンポと拍子を読み込みますか？
        ///（全トラックに反映されます。） 的本地化字符串。
        /// </summary>
        public static string MusicXmlImportConfirmationText {
            get {
                return ResourceManager.GetString("MusicXmlImportConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MusicXMLインポート 的本地化字符串。
        /// </summary>
        public static string MusicXmlImportDialogTitle {
            get {
                return ResourceManager.GetString("MusicXmlImportDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 音符のプロパティ 的本地化字符串。
        /// </summary>
        public static string NoteDialogTitle {
            get {
                return ResourceManager.GetString("NoteDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1音符1文字 的本地化字符串。
        /// </summary>
        public static string OneNoteOneMora {
            get {
                return ResourceManager.GetString("OneNoteOneMora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 音符毎に1文字ずつ割り当てます。
        ///小文字が続く場合のみ2文字割り当てられます。 的本地化字符串。
        /// </summary>
        public static string OneNoteOneMoraToolTip {
            get {
                return ResourceManager.GetString("OneNoteOneMoraToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 再生中はパラメータ計算できません 的本地化字符串。
        /// </summary>
        public static string ParametersCannotBeCalculated {
            get {
                return ResourceManager.GetString("ParametersCannotBeCalculated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 音素 的本地化字符串。
        /// </summary>
        public static string Phonemes {
            get {
                return ResourceManager.GetString("Phonemes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 英語 音素パレット 的本地化字符串。
        /// </summary>
        public static string PhoneticWindowTitleEn {
            get {
                return ResourceManager.GetString("PhoneticWindowTitleEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日本語 音素パレット 的本地化字符串。
        /// </summary>
        public static string PhoneticWindowTitleJa {
            get {
                return ResourceManager.GetString("PhoneticWindowTitleJa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 歌詞のまとめ入力(_I)... 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_EnterLyricsCollectively {
            get {
                return ResourceManager.GetString("PianoRollMenu_EnterLyricsCollectively", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 選択中または先頭の音符から歌詞をまとめて入力します。 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_EnterLyricsCollectivelyToolTip {
            get {
                return ResourceManager.GetString("PianoRollMenu_EnterLyricsCollectivelyToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 音素で歌詞入力(_P) 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_EnterLyricsWithPhoneme {
            get {
                return ResourceManager.GetString("PianoRollMenu_EnterLyricsWithPhoneme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 歌詞を音素記号で入力します。 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_EnterLyricsWithPhonemeToolTip {
            get {
                return ResourceManager.GetString("PianoRollMenu_EnterLyricsWithPhonemeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 細かい空白の除去(_F)... 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_FillSpaces {
            get {
                return ResourceManager.GetString("PianoRollMenu_FillSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 選択中または全音符の細かい隙間(休符)を埋めます。 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_FillSpacesToolTip {
            get {
                return ResourceManager.GetString("PianoRollMenu_FillSpacesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 調整モード(_M) 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_Mode {
            get {
                return ResourceManager.GetString("PianoRollMenu_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 楽譜を編集(_1) 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_Mode_Normal {
            get {
                return ResourceManager.GetString("PianoRollMenu_Mode_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 楽譜編集画面に切り替えます。 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_Mode_NormalToolTip {
            get {
                return ResourceManager.GetString("PianoRollMenu_Mode_NormalToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ピッチを調整(_4) 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_Mode_Pitch {
            get {
                return ResourceManager.GetString("PianoRollMenu_Mode_Pitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ピッチ調整画面に切り替えます。
        ///ビブラートの振幅や周期を重ねるとビブラート反映ピッチも重ね表示します。 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_Mode_PitchToolTip {
            get {
                return ResourceManager.GetString("PianoRollMenu_Mode_PitchToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 タイミングを調整(_2) 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_Mode_Timing {
            get {
                return ResourceManager.GetString("PianoRollMenu_Mode_Timing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 タイミング調整画面に切り替えます。 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_Mode_TimingToolTip {
            get {
                return ResourceManager.GetString("PianoRollMenu_Mode_TimingToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ビブラートの振幅を調整(_5) 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_Mode_VibratoAmplitude {
            get {
                return ResourceManager.GetString("PianoRollMenu_Mode_VibratoAmplitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ビブラートの振幅調整画面に切り替えます。 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_Mode_VibratoAmplitudeToolTip {
            get {
                return ResourceManager.GetString("PianoRollMenu_Mode_VibratoAmplitudeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ビブラートの周期を調整(_6) 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_Mode_VibratoFrequency {
            get {
                return ResourceManager.GetString("PianoRollMenu_Mode_VibratoFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ビブラートの周期調整画面に切り替えます。 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_Mode_VibratoFrequencyToolTip {
            get {
                return ResourceManager.GetString("PianoRollMenu_Mode_VibratoFrequencyToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ボリュームを調整(_3) 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_Mode_Volume {
            get {
                return ResourceManager.GetString("PianoRollMenu_Mode_Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ボリューム調整画面に切り替えます。 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_Mode_VolumeToolTip {
            get {
                return ResourceManager.GetString("PianoRollMenu_Mode_VolumeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 別トラックの音符(_P) 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_NotesOfOtherTracks {
            get {
                return ResourceManager.GetString("PianoRollMenu_NotesOfOtherTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 楽譜編集画面に別トラックの音符も表示します。
        ///（ミュートしたトラックの音符は表示しません。） 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_NotesOfOtherTracksToolTip {
            get {
                return ResourceManager.GetString("PianoRollMenu_NotesOfOtherTracksToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重ね表示(_P) 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_Overlay {
            get {
                return ResourceManager.GetString("PianoRollMenu_Overlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ピッチを表示(_4) 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_OverLay_Pitch {
            get {
                return ResourceManager.GetString("PianoRollMenu_OverLay_Pitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ピッチを重ねます。重ね表示にはビブラートを反映。 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_OverLay_PitchToolTip {
            get {
                return ResourceManager.GetString("PianoRollMenu_OverLay_PitchToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 タイミングを表示(_2) 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_OverLay_Timing {
            get {
                return ResourceManager.GetString("PianoRollMenu_OverLay_Timing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 タイミングを重ねます。 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_OverLay_TimingToolTip {
            get {
                return ResourceManager.GetString("PianoRollMenu_OverLay_TimingToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ビブラートの振幅を表示(_5) 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_OverLay_VibratoAmplitude {
            get {
                return ResourceManager.GetString("PianoRollMenu_OverLay_VibratoAmplitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ビブラートの振幅を重ねます。 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_OverLay_VibratoAmplitudeToolTip {
            get {
                return ResourceManager.GetString("PianoRollMenu_OverLay_VibratoAmplitudeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ビブラートの周期を表示(_6) 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_OverLay_VibratoFrequency {
            get {
                return ResourceManager.GetString("PianoRollMenu_OverLay_VibratoFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ビブラートの周期を重ねます。 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_OverLay_VibratoFrequencyToolTip {
            get {
                return ResourceManager.GetString("PianoRollMenu_OverLay_VibratoFrequencyToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ボリュームを表示(_3) 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_OverLay_Volume {
            get {
                return ResourceManager.GetString("PianoRollMenu_OverLay_Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ボリュームを重ねます。 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_OverLay_VolumeToolTip {
            get {
                return ResourceManager.GetString("PianoRollMenu_OverLay_VolumeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 プロパティ(_R)... 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_Properties {
            get {
                return ResourceManager.GetString("PianoRollMenu_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 音符の詳細、ブレスやスラーを設定します。
        ///音符を複数選択してまとめて変更可能。数値の+-指定可能。 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_PropertiesToolTip {
            get {
                return ResourceManager.GetString("PianoRollMenu_PropertiesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 テンポや拍子、調号の値を編集します。 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_PropertiesToolTip2 {
            get {
                return ResourceManager.GetString("PianoRollMenu_PropertiesToolTip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 クオンタイズ(_Q) 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_Quantize {
            get {
                return ResourceManager.GetString("PianoRollMenu_Quantize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1/16(3連符) 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_Quantize_Triplet16 {
            get {
                return ResourceManager.GetString("PianoRollMenu_Quantize_Triplet16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1/2(3連符) 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_Quantize_Triplet2 {
            get {
                return ResourceManager.GetString("PianoRollMenu_Quantize_Triplet2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1/4(3連符) 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_Quantize_Triplet4 {
            get {
                return ResourceManager.GetString("PianoRollMenu_Quantize_Triplet4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1/8(3連符) 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_Quantize_Triplet8 {
            get {
                return ResourceManager.GetString("PianoRollMenu_Quantize_Triplet8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 まとめ選択ツール(_2) 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_Tool_BulkSelect {
            get {
                return ResourceManager.GetString("PianoRollMenu_Tool_BulkSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 消しゴムツール(_5) 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_Tool_Eraser {
            get {
                return ResourceManager.GetString("PianoRollMenu_Tool_Eraser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ラインツール(_4) 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_Tool_Line {
            get {
                return ResourceManager.GetString("PianoRollMenu_Tool_Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ペンツール(_3) 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_Tool_Pen {
            get {
                return ResourceManager.GetString("PianoRollMenu_Tool_Pen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 選択ツール(_1) 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_Tool_Select {
            get {
                return ResourceManager.GetString("PianoRollMenu_Tool_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ビブラート無効(_V) 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_VibratoDisable {
            get {
                return ResourceManager.GetString("PianoRollMenu_VibratoDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 このトラック全体でビブラートを無効化します。 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_VibratoDisableToolTip {
            get {
                return ResourceManager.GetString("PianoRollMenu_VibratoDisableToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表示(_V) 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_View {
            get {
                return ResourceManager.GetString("PianoRollMenu_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拍のライン(_G) 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_View_BeatLine {
            get {
                return ResourceManager.GetString("PianoRollMenu_View_BeatLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拍のラインを表示します。 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_View_BeatLineToolTip {
            get {
                return ResourceManager.GetString("PianoRollMenu_View_BeatLineToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拍子行(_B) 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_View_BeatRow {
            get {
                return ResourceManager.GetString("PianoRollMenu_View_BeatRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ルーラーに拍子行を表示します。 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_View_BeatRowToolTip {
            get {
                return ResourceManager.GetString("PianoRollMenu_View_BeatRowToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 強弱記号行(_D) 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_View_DynamicsRow {
            get {
                return ResourceManager.GetString("PianoRollMenu_View_DynamicsRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ルーラーに強弱記号行を表示します。 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_View_DynamicsRowToolTip {
            get {
                return ResourceManager.GetString("PianoRollMenu_View_DynamicsRowToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ガイドカーソル(_C) 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_View_GuideLine {
            get {
                return ResourceManager.GetString("PianoRollMenu_View_GuideLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 クオンタイズの補助カーソルを表示します。 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_View_GuideLineToolTip {
            get {
                return ResourceManager.GetString("PianoRollMenu_View_GuideLineToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 調号行(_K) 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_View_KeyRow {
            get {
                return ResourceManager.GetString("PianoRollMenu_View_KeyRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ルーラーに調号(キー)行を表示します。 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_View_KeyRowToolTip {
            get {
                return ResourceManager.GetString("PianoRollMenu_View_KeyRowToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 クオンタイズのライン(_Q) 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_View_QuantizeLine {
            get {
                return ResourceManager.GetString("PianoRollMenu_View_QuantizeLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 クオンタイズのラインを表示します。 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_View_QuantizeLineToolTip {
            get {
                return ResourceManager.GetString("PianoRollMenu_View_QuantizeLineToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 テンポ行(_T) 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_View_TempoRow {
            get {
                return ResourceManager.GetString("PianoRollMenu_View_TempoRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ルーラーにテンポ行を表示します。 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_View_TempoRowToolTip {
            get {
                return ResourceManager.GetString("PianoRollMenu_View_TempoRowToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 調整画面にもライン表示(_V) 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_View_TuningLine {
            get {
                return ResourceManager.GetString("PianoRollMenu_View_TuningLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 調整画面にも拍やクオンタイズのラインを表示します。 的本地化字符串。
        /// </summary>
        public static string PianoRollMenu_View_TuningLineToolTip {
            get {
                return ResourceManager.GetString("PianoRollMenu_View_TuningLineToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 高さ 的本地化字符串。
        /// </summary>
        public static string Pitch {
            get {
                return ResourceManager.GetString("Pitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 位置 的本地化字符串。
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 スラー開始 的本地化字符串。
        /// </summary>
        public static string SlurBegin {
            get {
                return ResourceManager.GetString("SlurBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 スラー終了 的本地化字符串。
        /// </summary>
        public static string SlurEnd {
            get {
                return ResourceManager.GetString("SlurEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 スラー開始から終了までをなめらかに歌います。
        ///楽譜編集画面で音符を複数選択して[Ctrl+R]でも設定可能。 的本地化字符串。
        /// </summary>
        public static string SlurToolTip {
            get {
                return ResourceManager.GetString("SlurToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 音 的本地化字符串。
        /// </summary>
        public static string Sound {
            get {
                return ResourceManager.GetString("Sound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 スペース区切り 的本地化字符串。
        /// </summary>
        public static string SpaceDelimited {
            get {
                return ResourceManager.GetString("SpaceDelimited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 音符毎にスペースで区切られた文字を割り当てます。
        ///2文字以上の歌詞も割り当て可能です。 的本地化字符串。
        /// </summary>
        public static string SpaceDelimitedToolTip {
            get {
                return ResourceManager.GetString("SpaceDelimitedToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分割位置を調整(Ctrl+左クリックで既定位置) 的本地化字符串。
        /// </summary>
        public static string SplitterToolTip {
            get {
                return ResourceManager.GetString("SplitterToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 テンポ 的本地化字符串。
        /// </summary>
        public static string Tempo {
            get {
                return ResourceManager.GetString("Tempo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 テンポのプロパティ 的本地化字符串。
        /// </summary>
        public static string TempoDialogTitle {
            get {
                return ResourceManager.GetString("TempoDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 テンポ行(全トラック共通)
        ///ダブルクリックで編集。ドラッグで移動。追加はペンでダブルクリック。 的本地化字符串。
        /// </summary>
        public static string TempoRowToolTip {
            get {
                return ResourceManager.GetString("TempoRowToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ティック 的本地化字符串。
        /// </summary>
        public static string Tick {
            get {
                return ResourceManager.GetString("Tick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 トラック名 的本地化字符串。
        /// </summary>
        public static string TrackName {
            get {
                return ResourceManager.GetString("TrackName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ビブラート無効 的本地化字符串。
        /// </summary>
        public static string VibratoDisabled {
            get {
                return ResourceManager.GetString("VibratoDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 声質 的本地化字符串。
        /// </summary>
        public static string VoiceAlpha {
            get {
                return ResourceManager.GetString("VoiceAlpha", resourceCulture);
            }
        }
    }
}
