//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CeVIO.ToolBarControl.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CeVIO.ToolBarControl.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string ArrowButtonToolTip {
            get {
                return ResourceManager.GetString("ArrowButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string AutoScrollButtonToolTip {
            get {
                return ResourceManager.GetString("AutoScrollButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string BeginMarkerButtonToolTip {
            get {
                return ResourceManager.GetString("BeginMarkerButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string BulkButtonToolTip {
            get {
                return ResourceManager.GetString("BulkButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string EditAlphaButtonToolTip {
            get {
                return ResourceManager.GetString("EditAlphaButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string EditPitchButtonToolTip {
            get {
                return ResourceManager.GetString("EditPitchButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string EditScoreButtonToolTip {
            get {
                return ResourceManager.GetString("EditScoreButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string EditTimingButtonToolTip {
            get {
                return ResourceManager.GetString("EditTimingButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string EditVibratoAmplitudeButtonToolTip {
            get {
                return ResourceManager.GetString("EditVibratoAmplitudeButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string EditVibratoFrequencyButtonToolTip {
            get {
                return ResourceManager.GetString("EditVibratoFrequencyButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string EditVolumeButtonToolTip {
            get {
                return ResourceManager.GetString("EditVolumeButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string EndMarkerButtonToolTip {
            get {
                return ResourceManager.GetString("EndMarkerButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string EraserButtonToolTip {
            get {
                return ResourceManager.GetString("EraserButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string HeadButtonToolTip {
            get {
                return ResourceManager.GetString("HeadButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Indicator_BeatToolTip {
            get {
                return ResourceManager.GetString("Indicator_BeatToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Indicator_QuantizeMenu_Triplet16 {
            get {
                return ResourceManager.GetString("Indicator_QuantizeMenu_Triplet16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Indicator_QuantizeMenu_Triplet2 {
            get {
                return ResourceManager.GetString("Indicator_QuantizeMenu_Triplet2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Indicator_QuantizeMenu_Triplet4 {
            get {
                return ResourceManager.GetString("Indicator_QuantizeMenu_Triplet4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Indicator_QuantizeMenu_Triplet8 {
            get {
                return ResourceManager.GetString("Indicator_QuantizeMenu_Triplet8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Indicator_QuantizeToolTip {
            get {
                return ResourceManager.GetString("Indicator_QuantizeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Indicator_TempoToolTip {
            get {
                return ResourceManager.GetString("Indicator_TempoToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Indicator_TimeMenu_Bars {
            get {
                return ResourceManager.GetString("Indicator_TimeMenu_Bars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Indicator_TimeMenu_Seconds {
            get {
                return ResourceManager.GetString("Indicator_TimeMenu_Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Indicator_TimeToolTip {
            get {
                return ResourceManager.GetString("Indicator_TimeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string LineButtonToolTip {
            get {
                return ResourceManager.GetString("LineButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string MasterVolumeToolTipHead {
            get {
                return ResourceManager.GetString("MasterVolumeToolTipHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string MasterVolumeToolTipTail {
            get {
                return ResourceManager.GetString("MasterVolumeToolTipTail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string PenButtonToolTip {
            get {
                return ResourceManager.GetString("PenButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string PlayButtonToolTip {
            get {
                return ResourceManager.GetString("PlayButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string RepeatButtonToolTip {
            get {
                return ResourceManager.GetString("RepeatButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string ShowAlphaButtonToolTip {
            get {
                return ResourceManager.GetString("ShowAlphaButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string ShowPitchButtonToolTip {
            get {
                return ResourceManager.GetString("ShowPitchButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string ShowTimingButtonToolTip {
            get {
                return ResourceManager.GetString("ShowTimingButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string ShowVibratoAmplitudeButtonToolTip {
            get {
                return ResourceManager.GetString("ShowVibratoAmplitudeButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string ShowVibratoFrequencyButtonToolTip {
            get {
                return ResourceManager.GetString("ShowVibratoFrequencyButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string ShowVolumeButtonToolTip {
            get {
                return ResourceManager.GetString("ShowVolumeButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string StopButtonToolTip {
            get {
                return ResourceManager.GetString("StopButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string ToolBarMenu_HorizontalLocation {
            get {
                return ResourceManager.GetString("ToolBarMenu_HorizontalLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string ToolBarMenu_HorizontalLocationCenter {
            get {
                return ResourceManager.GetString("ToolBarMenu_HorizontalLocationCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string ToolBarMenu_HorizontalLocationLeft {
            get {
                return ResourceManager.GetString("ToolBarMenu_HorizontalLocationLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string ToolBarMenu_HorizontalLocationRight {
            get {
                return ResourceManager.GetString("ToolBarMenu_HorizontalLocationRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string ToolBarMenu_VerticalLocation {
            get {
                return ResourceManager.GetString("ToolBarMenu_VerticalLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string ToolBarMenu_VerticalLocationBottom {
            get {
                return ResourceManager.GetString("ToolBarMenu_VerticalLocationBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string ToolBarMenu_VerticalLocationMiddle {
            get {
                return ResourceManager.GetString("ToolBarMenu_VerticalLocationMiddle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string ToolBarMenu_VerticalLocationTop {
            get {
                return ResourceManager.GetString("ToolBarMenu_VerticalLocationTop", resourceCulture);
            }
        }
    }
}
